services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/subtitle_translator/logs
      - ./translated_subtitles:/app/subtitle_translator/translated_subtitles
      - /mnt/mediapool/movies:/movies
      - /mnt/mediapool/tvshows:/tvshows
    restart: unless-stopped
